services:
  - type: web
    name: kuravote-frontend
    runtime: node
    buildCommand: cd Kuravote && npm install --legacy-peer-deps && npm run build
    staticPublishPath: Kuravote/build
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
