services:
  - type: web
    name: kuravote-frontend
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    rootDirectory: Kuravote
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
      - key: REACT_APP_API_URL
        value: https://e-voting-backend-5087.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
