services:
  - type: web
    name: kuravote-frontend
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    rootDirectory: Kuravote
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
